name: CI with Continuous Validation

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Run static analysis
        run: pylint --exit-zero src/

      - name: Run unit tests
        run: pytest --junitxml=test-results.xml

      - name: Run security scan
        uses: github/codeql-action/analyze@v3
