name: Generate and Deploy Docs

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
          python -m pip install --upgrade pip
          pip install "pdoc<15"
          pdoc --html . --output-dir docs
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
